// Build step for the Cloudflare deploy. Runs LOCALLY, before committing.
//
//   npm run build          (cherga build)
//
// WHY IT RUNS BEFORE THE COMMIT, NOT IN CI
// The framework arrives through `file:../swc-js/*` optional dependencies —
// five packages from five subdirectories of one private repo, which npm cannot
// install from a git spec (npm/cli#513, open since 2012, no subdirectory
// selector). CI would therefore have to check out swc-js alongside this repo,
// and swc-js lives under a different GitHub org, so that needs a cross-org
// token this repository does not have.
//
// So the framework is folded in HERE, on a machine that already has the
// sibling checkout, and the results are COMMITTED:
//
//   dist/            static assets — bundle.js, bundle.css, shots
//   dist-worker/     the SSR worker with every import inlined, swc-js included
//
// The deploy then needs nothing but wrangler and this repository. That is the
// whole point: no framework in CI, no token, no sibling checkout.
//
// The cost is that the artefacts are committed and can go stale. Build before
// you commit — the pre-commit hook (tools/pre-commit) enforces it.

import { rm, writeFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import { join } from 'node:path';
import { appConfig } from '../app-config.js';

// cherga build emits the browser bundles and copies static assets, then calls
// this hook with those exact bytes and their framework content hash.
export default async function emitSite({ configDir: site, outDir: dist, compiled, version }) {
  const workerDist = join(site, 'dist-worker');
  const STATIC_ASSETS = ['shots', 'fonts'];
  await writeFile(join(dist, '_headers'), STATIC_ASSETS.map((a) => `/${a}/*\n  Cache-Control: public, max-age=31536000, immutable\n`).join('\n'));

  // ── 2. the manifest the worker reads at request time ─────────────────────────
  // The worker has no filesystem and no template when a request arrives, so the
  // bundle hash, the head meta extracted from index.html, and (when inlineCss is
  // on) the stylesheet BYTES have to be baked in here.
  await writeFile(join(site, 'worker', 'build-manifest.js'),
    `// Generated by tools/build-dist.mjs — do not hand-edit.
//
// CSS_TEXT carries the stylesheet ONLY when appConfig.inlineCss is on: the
// worker has no filesystem at request time, so inlining needs the bytes baked
// in. With the switch off this stays empty and the worker links the asset,
// which is what keeps flipping app-config.js sufficient on its own.
export const VERSION = '${version}';
export const HAS_ICONS_JS = ${Boolean(compiled.iconsJs)};
export const HAS_LEGACY_JS = ${Boolean(compiled.jsLegacy)};
export const INLINE_CSS = ${Boolean(appConfig.inlineCss)};
export const CSS_TEXT = ${JSON.stringify(appConfig.inlineCss ? (compiled.css || '') : '')};
export const CSS_LEGACY_TEXT = ${JSON.stringify(appConfig.inlineCss ? (compiled.cssLegacy || '') : '')};
export const META = ${JSON.stringify(compiled.meta || {})};
`);

  // ── 3. inline the worker and everything it imports ───────────────────────────
  // This is the step that removes the framework from CI. wrangler's bundler
  // follows worker/index.js through @cherga/* into the sibling checkout and
  // writes ONE self-contained file. wrangler.jsonc then uploads that verbatim
  // (no_bundle), so the deploy resolves nothing.
  //
  // Runs after the manifest write above: the worker imports build-manifest.js
  // and must see the fresh hash.
  await rm(workerDist, { recursive: true, force: true });
  const bundled = spawnSync('npx', [
    'wrangler', 'deploy', '--dry-run', '--outdir', workerDist, '--config', join(site, 'wrangler.build.jsonc'),
  ], { cwd: site, stdio: 'inherit' });
  if (bundled.status !== 0) {
    console.error('worker bundling failed — dist-worker not updated');
    process.exit(bundled.status || 1);
  }
  // wrangler side-products. Only index.js deploys, and committing a regenerated
  // source map on every build is pure churn in the diff.
  await Promise.all([
    rm(join(workerDist, 'index.js.map'), { force: true }),
    rm(join(workerDist, 'README.md'), { force: true }),
  ]);

  const kb = (n) => `${(n / 1024).toFixed(1)} KB`;
  console.log(`dist/ built (prod) · bundle.js ${kb(compiled.js.length)} · bundle.css ${kb((compiled.css || '').length)} · worker inlined · v=${version}`);
  console.log('commit dist/ and dist-worker/ — the deploy uses them verbatim.');
}
