// Build step for the Cloudflare deploy. Runs LOCALLY, before committing.
//
//   npm run build          (node tools/build-dist.mjs)
//
// WHY IT RUNS BEFORE THE COMMIT, NOT IN CI
// The framework arrives through `file:../swc-js/*` optional dependencies —
// four packages from four subdirectories of one private repo, which npm cannot
// install from a git spec (npm/cli#513, open since 2012, no subdirectory
// selector). CI would therefore have to check out swc-js alongside this repo,
// and swc-js lives under a different GitHub org, so that needs a cross-org
// token this repository does not have.
//
// So the framework is folded in HERE, on a machine that already has the
// sibling checkout, and the results are COMMITTED:
//
//   dist/            static assets — bundle.js, bundle.css, shots
//   dist-worker/     the SSR worker with every import inlined, swc-js included
//
// The deploy then needs nothing but wrangler and this repository. That is the
// whole point: no framework in CI, no token, no sibling checkout.
//
// The cost is that the artefacts are committed and can go stale. Build before
// you commit — the pre-commit hook (tools/pre-commit) enforces it.

import { cp, rm, mkdir, writeFile, access } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from '@swc-js/server/tools/build-lib.js';
import { appConfig } from '../app-config.js';

const site = dirname(fileURLToPath(import.meta.url)).replace(/\/tools$/, '');
const dist = join(site, 'dist');
const workerDist = join(site, 'dist-worker');

// Non-code assets the built app references by URL. CSS and JS are bundled;
// index.html's local .css links are folded into bundle.css by the framework
// build, and its font and icon links are carried into the worker's document
// through the generated manifest.
const STATIC_ASSETS = ['shots', 'fonts'];

// Fail early and legibly rather than with a module-resolution stack trace.
try {
  await access(join(site, 'node_modules', '@swc-js', 'server'));
} catch {
  console.error(`@swc-js/server is not resolvable.

The framework is linked from a sibling checkout. Expected:
  ${join(site, '..', 'swc-js')}

  git clone git@github.com:PragmaticalAI/swc-js.git ../swc-js
  npm install

This build inlines the framework, so it can only run where that checkout exists.`);
  process.exit(1);
}

// ── 1. bundle the app ────────────────────────────────────────────────────────
const compiled = await build(join(site, 'main.js'), { mode: 'prod' });

// Content hash for cache-busting bundle URLs, matching the framework server.
// The Safari variant participates: a polyfill change must roll the URLs too.
const version = createHash('sha1')
  .update(compiled.js).update(compiled.css || '').update(compiled.iconsJs || '')
  .update(compiled.jsSafari || '').update(compiled.cssLegacy || '').update(compiled.jsLegacy || '')
  .digest('hex').slice(0, 10);

await rm(dist, { recursive: true, force: true });
await mkdir(dist, { recursive: true });

await Promise.all([
  writeFile(join(dist, 'bundle.js'), compiled.js),
  compiled.jsMap ? writeFile(join(dist, 'bundle.js.map'), compiled.jsMap) : Promise.resolve(),
  // Safari build: the custom-elements polyfill prepended to the same bundle;
  // the worker picks it by user agent.
  writeFile(join(dist, 'bundle.safari.js'), compiled.jsSafari || compiled.js),
  writeFile(join(dist, 'bundle.css'), compiled.css || ''),
  compiled.cssLegacy ? writeFile(join(dist, 'bundle.legacy.css'), compiled.cssLegacy) : Promise.resolve(),
  compiled.jsLegacy ? writeFile(join(dist, 'bundle.legacy.js'), compiled.jsLegacy) : Promise.resolve(),
  compiled.iconsJs ? writeFile(join(dist, 'bundle.icons.js'), compiled.iconsJs) : Promise.resolve(),
  ...STATIC_ASSETS.map((a) => cp(join(site, a), join(dist, a), { recursive: true })),
  // Imagery is immutable by convention — a changed shot gets a new filename —
  // so it caches for a year at the edge and in the browser.
  writeFile(join(dist, '_headers'), STATIC_ASSETS.map((a) => `/${a}/*\n  Cache-Control: public, max-age=31536000, immutable\n`).join('\n')),
]);

// ── 2. the manifest the worker reads at request time ─────────────────────────
// The worker has no filesystem and no template when a request arrives, so the
// bundle hash, the head meta extracted from index.html, and (when inlineCss is
// on) the stylesheet BYTES have to be baked in here.
await writeFile(join(site, 'worker', 'build-manifest.js'),
  `// Generated by tools/build-dist.mjs — do not hand-edit.
//
// CSS_TEXT carries the stylesheet ONLY when appConfig.inlineCss is on: the
// worker has no filesystem at request time, so inlining needs the bytes baked
// in. With the switch off this stays empty and the worker links the asset,
// which is what keeps flipping app-config.js sufficient on its own.
export const VERSION = '${version}';
export const HAS_ICONS_JS = ${Boolean(compiled.iconsJs)};
export const HAS_LEGACY_JS = ${Boolean(compiled.jsLegacy)};
export const INLINE_CSS = ${Boolean(appConfig.inlineCss)};
export const CSS_TEXT = ${JSON.stringify(appConfig.inlineCss ? (compiled.css || '') : '')};
export const CSS_LEGACY_TEXT = ${JSON.stringify(appConfig.inlineCss ? (compiled.cssLegacy || '') : '')};
export const META = ${JSON.stringify(compiled.meta || {})};
`);

// ── 3. inline the worker and everything it imports ───────────────────────────
// This is the step that removes the framework from CI. wrangler's bundler
// follows worker/index.js through @swc-js/* into the sibling checkout and
// writes ONE self-contained file. wrangler.jsonc then uploads that verbatim
// (no_bundle), so the deploy resolves nothing.
//
// Runs after the manifest write above: the worker imports build-manifest.js
// and must see the fresh hash.
await rm(workerDist, { recursive: true, force: true });
const bundled = spawnSync('npx', [
  'wrangler', 'deploy', '--dry-run', '--outdir', workerDist, '--config', join(site, 'wrangler.build.jsonc'),
], { cwd: site, stdio: 'inherit' });
if (bundled.status !== 0) {
  console.error('worker bundling failed — dist-worker not updated');
  process.exit(bundled.status || 1);
}
// wrangler side-products. Only index.js deploys, and committing a regenerated
// source map on every build is pure churn in the diff.
await Promise.all([
  rm(join(workerDist, 'index.js.map'), { force: true }),
  rm(join(workerDist, 'README.md'), { force: true }),
]);

const kb = (n) => `${(n / 1024).toFixed(1)} KB`;
console.log(`dist/ built (prod) · bundle.js ${kb(compiled.js.length)} · bundle.css ${kb((compiled.css || '').length)} · worker inlined · v=${version}`);
console.log('commit dist/ and dist-worker/ — the deploy uses them verbatim.');
